### ISSUE TITLE
Use separate YAML files for each project

### ISSUE THREAD

**Issue by nodiscc** [n8225/awesome-selfhosted-gen#12]

**Comment by n8225** [comment]
@nodiscc YAML files are now created as of #23 .  The naming scheme probable needs some work.  files are named based on the source code URL.  I couldn't come up with anything better(not a fan of a numerical meaningless filenames).  Another possibility could be using the name and a number if it already exists, I'm fairly certain there are a couple duplicate names on the list right now.

**Comment by xy2z** [comment]
The list is very long, maybe it would be better to seperate into folders with the first letter? Altough maybe this requires some manual work...
Example:
- `lists/m/matomo.yaml`
- `lists/m/mailtrain.yaml`
etc.

We can't make folders for each "category" because some projects can be in multiple categories.

**Comment by nodiscc** [comment]
> The list is very long

it's less than 1300 files. Any program/parser/markdown-pdf-html-website renderer will handle it without problems. The only time YAML files will only used by humans, is for editing them. Even then, a single dir of ~1000, alphabetically orderd, uniquely-named YAML files _is_ readable/editable, better than a markdown list this size, and better than 26 directories of 0-20+ files. Keep it simple.

**Comment by nodiscc** [comment]
In progress at https://gitlab.com/nodiscc/hecat / https://github.com/nodiscc/hecat
